In [ ]:
#Download the NLTK CMU dataset 

In [4]:
nltk.download('cmudict')

[nltk_data] Downloading package cmudict to C:\Users\Gaurav
[nltk_data]     Choube\AppData\Roaming\nltk_data...
[nltk_data]   Package cmudict is already up-to-date!


True

In [2]:
import nltk
entries = nltk.corpus.cmudict.entries()
len(entries) #number of entries

133737

In [3]:
entries[:50] #here are the last fifty entries

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [5]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Gaurav
[nltk_data]     Choube\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [6]:
from nltk.corpus import wordnet as wn
wn.synsets('abandon')

[Synset('abandon.n.01'),
 Synset('wildness.n.01'),
 Synset('abandon.v.01'),
 Synset('abandon.v.02'),
 Synset('vacate.v.02'),
 Synset('abandon.v.04'),
 Synset('abandon.v.05')]

In [7]:
wn.synset('abandon.n.01').lemma_names()

['abandon', 'wantonness', 'unconstraint']

In [8]:
wn.synset('abandon.v.01').lemma_names()

['abandon']

In [9]:
wn.synset('abandon.v.02').lemma_names()

['abandon', 'give_up']

In [10]:
def gender_features(word):
    return {'last_letter':word[-1]}


In [11]:
gender_features('obama')

{'last_letter': 'a'}

In [12]:
nltk.download('names')

[nltk_data] Downloading package names to C:\Users\Gaurav
[nltk_data]     Choube\AppData\Roaming\nltk_data...
[nltk_data]   Package names is already up-to-date!


True

### Name Classifier

In [54]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
                 [(name, 'female') for name in names.words('female.txt')])

In [14]:
import random
random.shuffle(labeled_names)

In [15]:
featuresets = [(gender_features(n), gender) for (n,gender) in labeled_names]

In [16]:
train_set, test_set = featuresets[500:], featuresets[:500]

In [17]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)
classifier.classify(gender_features('Louis'))

'male'

In [52]:
a = classifier.classify(gender_features('obama'))
b = classifier.classify(gender_features('gaurav'))
c = classifier.classify(gender_features('trump'))
d = classifier.classify(gender_features('Bini'))
e = classifier.classify(gender_features('Meni'))
f = classifier.classify(gender_features('sonal'))
g = classifier.classify(gender_features('Avery'))


#### Critical observation

* The model is classified in such a manner that the names ending with vowels always are considered as female but the model fails when the name ending with vowel is a male, also if the female names don't end with a vowel all the common names are taken and classified in their respective category.


* For example, Avery for a female is a common name and is classified into feamle name but we should also note that the name does not end with a vowel. So, the conclusion can be taken into the account that common names are classified into their respective category.


* Look for the name Sonal, where it is classified into male although it's a female name, so one more observation can be made that the rule is followed for the names which is common in English speaking countries and may or may not work for countries whose native language is english so the accuracy is around 75%, still the model works fine most of the time  

In [53]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

female
male
male
female
female
male
female


In [55]:
print(nltk.classify.accuracy(classifier, test_set))  #accuracy to test whether male or female

0.73


In [32]:
from sklearn.feature_extraction.text import CountVectorizer   
#importing count vectorizer and transfroming into an numerical format

In [57]:
vect = CountVectorizer(binary=True)
corpus = ["Teseract is good optical character recognition engine","optical character engine is significant"]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [34]:
vocab = vect.vocabulary_

In [35]:
#forming a key-value pair for the vocabulary
for key in sorted(vocab.keys()):
    print("{}:{}".format(key,vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
teseract:7


In [36]:
print(vect.transform(["This is a good optical illusion"]).toarray()) #tranform into vector format example 1

[[0 0 1 1 1 0 0 0]]


In [37]:
print(vect.transform(corpus).toarray())  #tranform into vector format example 2

[[1 1 1 1 1 1 0 1]
 [1 1 0 1 1 0 1 0]]


In [38]:
from sklearn.metrics.pairwise import cosine_similarity  #import cosine similarity 

In [58]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())
similarity1 = cosine_similarity(vect.transform(["We develop state of art technology and transfrom today's world"]).toarray(), vect.transform(["We continue to serve our clients with state-of-the-art technology and a creative vision for tomorrow's challenges."]).toarray())

In [59]:
print(similarity)   #cosine similarity for first one 
print(similarity1)  #cosine similarity for second one 

[[0.89442719]]
[[0.]]


In [43]:
similarity

array([[0.89442719]])

In [60]:
similarity1

array([[0.]])

### Check for the result

Comparing two local documents using cosine similarity, to check the result of cosine similarity we've used the same documents whether it gives the result zero or not

In [61]:
similarity2 = cosine_similarity(vect.transform(["F:\M.Tech Sem 1-2\CSE6024 -- Machine Learning Techniques\DA\ML-DA.docx"]).toarray(), vect.transform(["F:\M.Tech Sem 1-2\CSE6024 -- Machine Learning Techniques\DA\ML-DA.docx"]).toarray())

In [62]:
print(similarity2)
similarity2

[[0.]]


array([[0.]])